### ISSUE TITLE
Not possible to merge with upstream

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/Genesis-Plus-GX#82]
It's not possible to merge with upstream anymore due changes in core/cd_hw/cdd.c, ekeeke touch there too: https://github.com/ekeeke/Genesis-Plus-GX/commit/2a19462f0dbbb2400835721b4a234c0a9230db01

#81 

@albertofustinoni

**Comment by sergiobenrocha2** [comment]
And now it's segfaulting if I try to load a Sega CD game with ogg files. It segfaults only if I try to load in the terminal.

```
(gdb) run
Starting program: /usr/bin/retroarch -L genesis_plus_gx_libretro.so /home/sergio2/Games/ROMs/Sega\ CD/Sonic\ The\ Hedgehog\ CD\ \(Japan\)/Sonic\ The\ Hedgehog\ CD\ \(Japan\).cue
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffde550700 (LWP 16915)]
Fatal error: glibc detected an invalid stdio handle

Thread 1 "retroarch" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
(gdb) 
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
        set = {__val = {0, 140737351915147, 1185, 140737215696952, 140737352197032, 140737488326216, 140737488326212, 140737351913489, 13170, 140736893856750, 140736893855344, 140737488326216, 221883709, 3466932, 61, 
            140737215696952}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007fffefc1f37a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7383353, sa_sigaction = 0x7383353}, sa_mask = {__val = {140737351916433, 140737215671464, 140737352197032, 5, 0, 1, 93825010878976, 140737488326672, 884, 0, 
              93825010879832, 140737488326576, 8453494411, 93825010878976, 52, 140737488326816}}, sa_flags = 52, sa_restorer = 0x7fffffff8fc0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fffefc61090 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fffefd753b3 "%s") at ../sysdeps/posix/libc_fatal.c:175
        ap = {{gp_offset = 24, fp_offset = 32767, overflow_arg_area = 0x7fffffff90b0, reg_save_area = 0x7fffffff9040}}
        fd = 6
        on_2 = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
        written = <optimized out>
#3  0x00007fffefc610d2 in __GI___libc_fatal (message=message@entry=0x7fffefd76f40 "Fatal error: glibc detected an invalid stdio handle\n") at ../sysdeps/posix/libc_fatal.c:185
No locals.
#4  0x00007fffefc618d6 in _IO_vtable_check () at vtables.c:71
        flag = <optimized out>
#5  0x00007fffefc65a6c in IO_validate_vtable (vtable=0xb01965a6) at libioP.h:942
        section_length = <optimized out>
        ptr = 0xb01965a6 <error: Cannot access memory at address 0xb01965a6>
        offset = <optimized out>
#6  __GI__IO_sgetn (fp=0x55555670b070, data=0x1, n=1024) at genops.c:467
No locals.
#7  0x00007fffefc57469 in __GI__IO_fread (buf=<optimized out>, size=1, count=1024, fp=0x55555670b070) at iofread.c:38
        _IO_acquire_lock_file = 0x55555670b070
        bytes_requested = 1024
        bytes_read = <optimized out>
#8  0x00007fffdcd20ff9 in filestream_read (stream=0x55555670b080, s=0x1, len=1024) at libretro-common/streams/file_stream.c:464
No locals.
#9  0x00007fffdcd24e0c in _get_data (vf=0x7fffddcdbfa8 <ext+10187048>) at core/tremor/vorbisfile.c:65
        buffer = 0x55555670b080 "آ\372\357\377\177"
        bytes = -1645065058439232768
#10 0x00007fffdcd24f5b in _get_next_page (vf=0x7fffddcdbfa8 <ext+10187048>, og=0x7fffffff9270, boundary=1024) at core/tremor/vorbisfile.c:128
        ret = 472446402651
        more = 0
#11 0x00007fffdcd2543f in _fetch_headers (vf=0x7fffddcdbfa8 <ext+10187048>, vi=0x555556707e40, vc=0x555556707e80, serialno=0x7fffddcdc014 <ext+10187156>, og_ptr=0x0) at core/tremor/vorbisfile.c:256
        llret = 93825012405984
        og = {header = 0x0, header_len = 0, body = 0x0, body_len = 0}
        op = {packet = 0x0, bytes = 0, b_o_s = 0, e_o_s = 0, granulepos = 0, packetno = 0}
        i = 0
        ret = 2336
#12 0x00007fffdcd26679 in _ov_open1 (f=0x55555671f3a0, vf=0x7fffddcdbfa8 <ext+10187048>, initial=0x0, ibytes=0, callbacks=...) at core/tremor/vorbisfile.c:708
        offsettest = 0
        ret = 0
#13 0x00007fffdcd26903 in ov_open_callbacks (f=0x55555671f3a0, vf=0x7fffddcdbfa8 <ext+10187048>, initial=0x0, ibytes=0, callbacks=...) at core/tremor/vorbisfile.c:772
        ret = 32767
#14 0x00007fffdcd0481c in cdd_load (filename=0x555556707510 "/home/sergio2/Games/ROMs/Sega CD/Sonic The Hedgehog CD (Japan)/Sonic The Hedgehog CD (Japan).cue", header=0x7fffdd324ee0 <ext+96> "SEGADISCSYSTEM  SEGAIPSAMP ")
    at core/cd_hw/cdd.c:512
        head = "\000\000\000\000\000\000\065C\251F\000\000\000\000x\002\374\370\001\036\001vorbis"
        mm = 0
        ss = 0
        bb = 0
        pregap = 0
        fname = "/home/sergio2/Games/ROMs/Sega CD/Sonic The Hedgehog CD (Japan)/Sonic The Hedgehog CD (Japan) (Track 02).ogg", '\000' <repeats 149 times>...
        line = "FILE \"Sonic The Hedgehog CD (Japan) (Track 02).ogg\" OGG\r\n\000\r\n\000\177\000\000\377\000\000\000\000\000\000\000\033\312\326\334\377\177\000\000\370\225\377\377\377\177\000\000p\177pVUU\000\000`\365\324\335\377\177\000\000\031\003\306\357\377\177\000\000\001\200\255\373\000\000\000\000`\365\324\335\377\177\000"
        ptr = 0x7fffffff950b ""
        lptr = 0x7fffffff9452 "\" OGG\r\n"
        fd = 0x555556705350
        isCDfile = 1
#15 0x00007fffdcc1c2f8 in load_rom (filename=0x555556707510 "/home/sergio2/Games/ROMs/Sega CD/Sonic The Hedgehog CD (Japan)/Sonic The Hedgehog CD (Japan).cue") at core/loadrom.c:555
        i = 0
        size = 48
#16 0x00007fffdcd39651 in retro_load_game (info=0x555556707fb0) at libretro/libretro.c:2065
        i = 21845
        dir = 0x7fffde573786 "/home/sergio2/Games/RetroArch/system"
        slash = 47 '/'
#17 0x00005555555b0ca9 in core_load_game (load_info=load_info@entry=0x7fffffff9800) at core_impl.c:289
        contentless = false
        is_inited = true
#18 0x00005555555c592e in content_file_load (info=info@entry=0x555556707fb0, content=content@entry=0x555556707f70, content_ctx=content_ctx@entry=0x7fffffffc090, error_string=error_string@entry=0x7fffffffc080, special=0x0, 
    additional_path_allocs=additional_path_allocs@entry=0x55555671f110) at tasks/task_content.c:581
        i = <optimized out>
        load_info = {info = 0x555556707fb0, content = 0x555556707f70, special = 0x0}
        msg = "\000\064T\034L\001\364\372\256\374\347\373\062\016\237,\355\064V\034M\001\364\372\257\374\347\373\061\016\235,\356\064X\034N\001\364\372\257\374\346\373/\016\233,\356\064Z\034O\001\364\372\257\374\346\373-\016\232,\357\064\\\034P\001\364\372\260\374\345\373+\016\230,\360\064^\034Q\001\364\372\260\374\345\373)\016\227,\360\064`\034R\001\364\372\260\374\345\373(\016\225,\361\064c\034T\001\363\372\260\374\344\373&\016\224,\362\064e\034U\001\363\372\261\374\344\373$\016\222,\362\064g\034V\001\363\372\261\374\343\373\"\016\221,\363\064i\034W\001\363\372\261\374\343\373 \016\217,\364\064k\034X\001\363\372\262\374\343\373\036\016\215,\364\064m\034Y\001\363\372"...
#19 0x00005555555c785d in content_file_init (error_string=0x7fffffffc080, content=0x555556707f70, content_ctx=0x7fffffffc090) at tasks/task_content.c:750
        i = <optimized out>
        additional_path_allocs = 0x55555671f110
        info = 0x555556707fb0
        ret = true
        special = <optimized out>
#20 content_init () at tasks/task_content.c:1741
        content_ctx = {subsystem = {data = 0x0, size = 0}, name_ips = 0x5555567071b0 "/home/sergio2/Games/ROMs/Sega CD/Sonic The Hedgehog CD (Japan)/Sonic The Hedgehog CD (Japan).ips", 
          name_bps = 0x555556707220 "/home/sergio2/Games/ROMs/Sega CD/Sonic The Hedgehog CD (Japan)/Sonic The Hedgehog CD (Japan).bps", 
          name_ups = 0x555556707290 "/home/sergio2/Games/ROMs/Sega CD/Sonic The Hedgehog CD (Japan)/Sonic The Hedgehog CD (Japan).ups", valid_extensions = 0x555556707fe0 "mdx|md|smd|gen|bin|cue|iso|sms|gg|sg", 
          directory_cache = 0x555556707f90 "/tmp", directory_system = 0x555556706d00 "/home/sergio2/Games/RetroArch/system", is_ips_pref = false, is_bps_pref = false, is_ups_pref = false, history_list_enable = true, 
          block_extract = false, need_fullpath = true, set_supports_no_game_enable = true, patch_is_blocked = false, bios_is_missing = 192, check_firmware_before_loading = false, temporary_content = 0x55555671f130}
        ret = true
        error_string = 0x0
        content = 0x555556707f70
        global = <optimized out>
        settings = <optimized out>
        sys_info = <optimized out>
#21 0x00005555555bae99 in event_init_content () at command.c:1192
        contentless = false
        is_inited = false
#22 command_event_init_core (data=0x555555cbf044 <current_core_type>) at command.c:1250
        info = {env = 0x5555555fb240 <rarch_environment_cb>}
        settings = 0x7fffde551010
#23 command_event (cmd=cmd@entry=CMD_EVENT_CORE_INIT, data=data@entry=0x555555cbf044 <current_core_type>) at command.c:2065
        boolean = false
#24 0x00005555555b58cd in retroarch_main_init (argc=4, argv=argv@entry=0x7fffffffdee8) at retroarch.c:1252
No locals.
#25 0x00005555555c43e7 in content_load (info=0x7fffffffddb0) at tasks/task_content.c:276
        i = <optimized out>
        retval = true
        rarch_argc = 0
        rarch_argv_ptr = 0x7fffffffdee8
        rarch_argv = {0x0 <repeats 32 times>}
        argv_copy = {0x0 <repeats 32 times>}
        rarch_argc_ptr = 0x7fffffffddb0
        wrap_args = 0x5555566e4a80
#26 task_load_content (content_info=content_info@entry=0x7fffffffddb0, content_ctx=content_ctx@entry=0x7fffffffdd10, launched_from_menu=launched_from_menu@entry=true, launched_from_cli=launched_from_cli@entry=true, 
    error_string=error_string@entry=0x7fffffffdd08) at tasks/task_content.c:821
        name = "\000\066\240\"2\005\300\372\235\375\372\372\322\b>'I6\242\"4\005\300\372\235\375\372\372\320\b<'I6\244\"5\005\300\372\235\375\372\372\317\b:'I6\246\"6\005\300\372\236\375\372\372\315\b8'I6\250\"8\005\300\372\236\375\371\372\314\b6'J6\252\"9\005\300\372\236\375\371\372\312\b5'J6\254\";\005\300\372\237\375\371\372\310\b3'J6\256\"<\005\300\372\237\375\371\372\307\b1'J6\260\"=\005\300\372\237\375\371\372\305\b/'J6\262\"?\005\300\372\237\375\371\372\304\b-'K6\264\"@\005\300\372\240\375\370\372\302\b+'K6\266\"B\005\300\372\240\375\370\372\301\b*'K6\270\"C\005\300\372"...
        msg = "\000\066\277\"H\005\300\372\241\375\367\372\271\b 'L6\301\"J\005\300\372\242\375\367\372\267\b\037'L6\303\"K\005\300\372\242\375\367\372\266\b\035'L6\305\"M\005\300\372\242\375\367\372\264\b\033'L6\307\"N\005\300\372\243\375\367\372\262\b\031'M6\311\"O\005\300\372\243\375\367\372\261\b\027'M6\313\"Q\005\300\372\243\375\366\372\257\b\025'M6\315\"R\005\300\372\243\375\366\372\256\b\024'M6\317\"T\005\300\372\244\375\366\372\254\b\022'M6\321\"U\005\300\372\244\375\366\372\252\b\020'M6\323\"V\005\300\372\244\375\366\372\251\b\016'N6\325\"X\005\300\372\245\375\366\372\247\b\f'N6\327\"Y\005\300\372"...
        contentless = false
        is_inited = false
#27 0x00005555555c5379 in task_load_content_callback (content_info=0x7fffffffddb0, loading_from_cli=<optimized out>, loading_from_menu=true) at tasks/task_content.c:1473
        content_ctx = {subsystem = {data = 0x0, size = 0}, name_ips = 0x0, name_bps = 0x0, name_ups = 0x0, valid_extensions = 0x0, directory_cache = 0x0, directory_system = 0x0, is_ips_pref = false, is_bps_pref = false, 
          is_ups_pref = false, history_list_enable = false, block_extract = false, need_fullpath = false, set_supports_no_game_enable = false, patch_is_blocked = false, bios_is_missing = false, 
          check_firmware_before_loading = false, temporary_content = 0x7fffffffdee8}
        ret = false
        error_string = 0x0
        global = <optimized out>
        settings = 0x7fffde551010
#28 0x00005555555afd69 in rarch_main (argc=4, argv=0x7fffffffdee8, data=0x0) at frontend/frontend.c:115
        info = {argc = 4, argv = 0x7fffffffdee8, args = 0x0, environ_get = 0x5555555aedb0 <frontend_unix_get_env>}
        args = 0x0
#29 0x00007fffefc083f1 in __libc_start_main (main=0x5555555ab390 <main>, argc=4, argv=0x7fffffffdee8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffded8) at ../csu/libc-start.c:291
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 3379527723151071401, 93824992596000, 140737488346848, 0, 0, 8913514721580226729, 8913479183065356457}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffffffdf10, 
              0x7ffff7ffe168}, data = {prev = 0x0, cleanup = 0x0, canceltype = -8432}}}
        not_first_call = <optimized out>
#30 0x00005555555ad04a in _start ()
No symbol table info available.
```

**Comment by sergiobenrocha2** [comment]
Load it by Load Content, you'll get no CD music audio

**Comment by ekeeke** [comment]
This can be closed
